package com.akrapovic.soundkit.community.ui.theme

import androidx.annotation.DrawableRes
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color
import com.akrapovic.soundkit.community.R

/**
 * Provides the active [GarageTheme] down the Composition tree.
 * Read via `LocalAkraTheme.current` in any Composable.
 * Set via `CompositionLocalProvider` inside [SoundKitTheme].
 */
val LocalAkraTheme = compositionLocalOf { GarageThemePresets.first() }

data class GarageTheme(
    val id: String,
    val name: String,
    val subtitle: String,
    @DrawableRes val brandMark: Int = 0,
    val base: Color,
    val surface: Color,
    val accent: Color,
    val secondaryAccent: Color,
    val highlight: Color,
    val isDark: Boolean = true,
    val gradientStart: Color = base,
    val gradientEnd: Color = surface,
    val cardGradientStart: Color = surface,
    val cardGradientEnd: Color = surface,
    val onBase: Color = if (isDark) AkraColors.Silver else Color(0xFF1C1C1E),
    val onSurface: Color = if (isDark) AkraColors.Pearl else Color(0xFF111111),
    val muted: Color = if (isDark) AkraColors.Mist else Color(0xFF6E6E73),
)

data class GarageThemeFamily(
    val id: String,
    val name: String,
    val subtitle: String,
    @DrawableRes val brandMark: Int = 0,
    val dark: GarageTheme,
    val light: GarageTheme,
) {
    fun contains(themeId: String): Boolean = dark.id == themeId || light.id == themeId
}

val GarageThemeFamilies = listOf(
    GarageThemeFamily(
        id = "studio",
        name = "Studio",
        subtitle = "Clean Sound Kit product styling without a car brand mark.",
        brandMark = R.drawable.brand_studio,
        dark = GarageTheme(
            id = "studio-dark",
            name = "Studio Black",
            subtitle = "Default black and white product style with restrained Sound Kit accents.",
            brandMark = R.drawable.brand_studio,
            base = AkraColors.Ink,
            surface = AkraColors.Carbon,
            accent = AkraColors.Pearl,
            secondaryAccent = AkraColors.Titanium,
            highlight = AkraColors.Mist,
            gradientStart = Color(0xFF000000),
            gradientEnd = Color(0xFF171717),
            cardGradientStart = Color(0xFF191919),
            cardGradientEnd = Color(0xFF101010),
        ),
        light = GarageTheme(
            id = "studio-light",
            name = "Studio Light",
            subtitle = "A clean light mode with soft gray gradients and black primary controls.",
            brandMark = R.drawable.brand_studio,
            base = AkraColors.LightBackground,
            surface = AkraColors.LightSurface,
            accent = AkraColors.LightText,
            secondaryAccent = AkraColors.LightMuted,
            highlight = Color(0xFFE8E8ED),
            isDark = false,
            gradientStart = Color(0xFFFFFFFF),
            gradientEnd = Color(0xFFEDEDF2),
            cardGradientStart = Color(0xFFFFFFFF),
            cardGradientEnd = Color(0xFFF1F1F5),
        ),
    ),
    GarageThemeFamily(
        id = "akrapovic",
        name = "Akrapovic",
        subtitle = "Dark exhaust-inspired palette with a clean performance mark.",
        brandMark = R.drawable.brand_akra,
        dark = darkTheme(
            id = "akrapovic-dark",
            name = "Akrapovic Dark",
            subtitle = "Black titanium surfaces with warm exhaust amber.",
            brandMark = R.drawable.brand_akra,
            base = Color(0xFF070604),
            surface = Color(0xFF14110D),
            accent = AkraColors.AmberHi,
            secondaryAccent = AkraColors.Amber,
            highlight = AkraColors.Pearl,
        ),
        light = lightTheme(
            id = "akrapovic-light",
            name = "Akrapovic Light",
            subtitle = "Warm light surfaces with titanium and amber detail.",
            brandMark = R.drawable.brand_akra,
            tint = Color(0xFFFFF7E8),
            accent = Color(0xFF7A5A11),
            secondaryAccent = AkraColors.Amber,
        ),
    ),
    GarageThemeFamily(
        id = "audi-rs",
        name = "Audi RS",
        subtitle = "RS3-inspired red signal, graphite surfaces, and glacier highlights.",
        brandMark = R.drawable.brand_audi_rs,
        dark = darkTheme(
            id = "audi-rs-dark",
            name = "Audi RS Dark",
            subtitle = "Graphite cabin, cool white linework, restrained RS red signal.",
            brandMark = R.drawable.brand_audi_rs,
            base = Color(0xFF07090C),
            surface = Color(0xFF151922),
            accent = Color(0xFFE8EBF0),
            secondaryAccent = Color(0xFFD21F2B),
            highlight = AkraColors.Amber,
        ),
        light = lightTheme(
            id = "audi-rs-light",
            name = "Audi RS Light",
            subtitle = "Glacier white surfaces with RS red control accents.",
            brandMark = R.drawable.brand_audi_rs,
            tint = Color(0xFFFFF3F4),
            accent = Color(0xFFB41522),
            secondaryAccent = Color(0xFFD21F2B),
        ),
    ),
    GarageThemeFamily(
        id = "bmw-m",
        name = "BMW M",
        subtitle = "Blue, violet, and red performance stripes on focused surfaces.",
        brandMark = R.drawable.brand_bmw_m,
        dark = darkTheme(
            id = "bmw-m-dark",
            name = "BMW M Dark",
            subtitle = "Black base with blue, violet, and red motorsport stripes.",
            brandMark = R.drawable.brand_bmw_m,
            base = Color(0xFF07090D),
            surface = Color(0xFF121721),
            accent = Color(0xFF2D9CDB),
            secondaryAccent = Color(0xFF7B3FF2),
            highlight = Color(0xFFE21B2D),
        ),
        light = lightTheme(
            id = "bmw-m-light",
            name = "BMW M Light",
            subtitle = "Light cockpit with crisp M blue and red highlights.",
            brandMark = R.drawable.brand_bmw_m,
            tint = Color(0xFFEFF7FF),
            accent = Color(0xFF0066B1),
            secondaryAccent = Color(0xFFE21B2D),
        ),
    ),
    GarageThemeFamily(
        id = "mercedes-amg",
        name = "Mercedes-AMG",
        subtitle = "Silver edgework with a focused green performance spark.",
        brandMark = R.drawable.brand_mercedes_amg,
        dark = darkTheme(
            id = "mercedes-amg-dark",
            name = "Mercedes-AMG Dark",
            subtitle = "Obsidian cockpit with silver edgework and green performance spark.",
            brandMark = R.drawable.brand_mercedes_amg,
            base = Color(0xFF070807),
            surface = Color(0xFF151716),
            accent = Color(0xFFD7DCE2),
            secondaryAccent = Color(0xFF00A859),
            highlight = AkraColors.Amber,
        ),
        light = lightTheme(
            id = "mercedes-amg-light",
            name = "Mercedes-AMG Light",
            subtitle = "Silver-white surfaces with a restrained AMG green signal.",
            brandMark = R.drawable.brand_mercedes_amg,
            tint = Color(0xFFF2FFF7),
            accent = Color(0xFF007A43),
            secondaryAccent = Color(0xFF00A859),
        ),
    ),
    GarageThemeFamily(
        id = "porsche",
        name = "Porsche",
        subtitle = "Warm ivory, guards red, and black instrument contrast.",
        brandMark = R.drawable.brand_porsche,
        dark = darkTheme(
            id = "porsche-dark",
            name = "Porsche Dark",
            subtitle = "Deep black, guards red, warm ivory instrument highlights.",
            brandMark = R.drawable.brand_porsche,
            base = Color(0xFF090909),
            surface = Color(0xFF151311),
            accent = Color(0xFFEACD8A),
            secondaryAccent = Color(0xFFD5001C),
            highlight = AkraColors.Amber,
        ),
        light = lightTheme(
            id = "porsche-light",
            name = "Porsche Light",
            subtitle = "Warm light surfaces with guards red primary action.",
            brandMark = R.drawable.brand_porsche,
            tint = Color(0xFFFFF8EA),
            accent = Color(0xFFB00018),
            secondaryAccent = Color(0xFFD5001C),
        ),
    ),
    GarageThemeFamily(
        id = "volkswagen-r",
        name = "Volkswagen R",
        subtitle = "Electric blue performance detail with crisp neutral surfaces.",
        brandMark = R.drawable.brand_vw_r,
        dark = darkTheme(
            id = "volkswagen-r-dark",
            name = "Volkswagen R Dark",
            subtitle = "Dark cabin with electric blue performance accent.",
            brandMark = R.drawable.brand_vw_r,
            base = Color(0xFF070A10),
            surface = Color(0xFF101826),
            accent = Color(0xFF4EA3FF),
            secondaryAccent = Color(0xFF95B8FF),
            highlight = AkraColors.Pearl,
        ),
        light = lightTheme(
            id = "volkswagen-r-light",
            name = "Volkswagen R Light",
            subtitle = "White glass surfaces with electric R blue accents.",
            brandMark = R.drawable.brand_vw_r,
            tint = Color(0xFFEFF6FF),
            accent = Color(0xFF006EDB),
            secondaryAccent = Color(0xFF4EA3FF),
        ),
    ),
    GarageThemeFamily(
        id = "lamborghini",
        name = "Lamborghini",
        subtitle = "Sharp green and amber supercar contrast.",
        brandMark = R.drawable.brand_lamborghini,
        dark = darkTheme(
            id = "lamborghini-dark",
            name = "Lamborghini Dark",
            subtitle = "Stealth black with sharp green and amber supercar contrast.",
            brandMark = R.drawable.brand_lamborghini,
            base = Color(0xFF060806),
            surface = Color(0xFF111611),
            accent = Color(0xFFB4FF00),
            secondaryAccent = Color(0xFFFFD54A),
            highlight = AkraColors.Pearl,
        ),
        light = lightTheme(
            id = "lamborghini-light",
            name = "Lamborghini Light",
            subtitle = "Light surfaces with supercar green and amber detail.",
            brandMark = R.drawable.brand_lamborghini,
            tint = Color(0xFFF8FFE8),
            accent = Color(0xFF527A00),
            secondaryAccent = Color(0xFFB4FF00),
        ),
    ),
)

val GarageThemePresets: List<GarageTheme> = GarageThemeFamilies.flatMap { family ->
    listOf(family.dark, family.light)
}

private fun darkTheme(
    id: String,
    name: String,
    subtitle: String,
    @DrawableRes brandMark: Int,
    base: Color,
    surface: Color,
    accent: Color,
    secondaryAccent: Color,
    highlight: Color,
): GarageTheme = GarageTheme(
    id = id,
    name = name,
    subtitle = subtitle,
    brandMark = brandMark,
    base = base,
    surface = surface,
    accent = accent,
    secondaryAccent = secondaryAccent,
    highlight = highlight,
    gradientStart = base,
    gradientEnd = surface,
    cardGradientStart = surface.copy(alpha = 1f),
    cardGradientEnd = base.copy(alpha = 1f),
)

private fun lightTheme(
    id: String,
    name: String,
    subtitle: String,
    @DrawableRes brandMark: Int,
    tint: Color,
    accent: Color,
    secondaryAccent: Color,
): GarageTheme = GarageTheme(
    id = id,
    name = name,
    subtitle = subtitle,
    brandMark = brandMark,
    base = tint,
    surface = AkraColors.LightSurface,
    accent = accent,
    secondaryAccent = secondaryAccent,
    highlight = Color(0xFFE7E7EC),
    isDark = false,
    gradientStart = AkraColors.LightSurface,
    gradientEnd = tint,
    cardGradientStart = AkraColors.LightSurface,
    cardGradientEnd = tint.copy(alpha = 1f),
    onBase = AkraColors.LightText,
    onSurface = AkraColors.LightText,
    muted = AkraColors.LightMuted,
)
