package com.akrapovic.soundkit.community.ui.theme

import androidx.compose.ui.graphics.Color

data class GarageTheme(
    val id: String,
    val name: String,
    val subtitle: String,
    val base: Color,
    val surface: Color,
    val accent: Color,
    val secondaryAccent: Color,
    val highlight: Color,
)

val GarageThemePresets = listOf(
    GarageTheme(
        id = "akra-carbon",
        name = "Akrapovic / Carbon",
        subtitle = "Default dark titanium and amber Sound Kit identity.",
        base = AkraColors.Ink,
        surface = AkraColors.Carbon,
        accent = AkraColors.Amber,
        secondaryAccent = AkraColors.Titanium,
        highlight = AkraColors.Pearl,
    ),
    GarageTheme(
        id = "audi-rs3-white-sportback",
        name = "Audi RS3 White Sportback",
        subtitle = "Your 2026 RS3: black cockpit, glacier white highlights, subtle RS red.",
        base = Color(0xFF080A0D),
        surface = Color(0xFF12161C),
        accent = Color(0xFFE8EBF0),
        secondaryAccent = Color(0xFFD21F2B),
        highlight = AkraColors.Amber,
    ),
    GarageTheme(
        id = "audi-rs-dark",
        name = "Audi / RS Dark",
        subtitle = "Graphite cabin, cool white linework, restrained RS red signal.",
        base = Color(0xFF07090C),
        surface = Color(0xFF151922),
        accent = Color(0xFFC9D1DA),
        secondaryAccent = Color(0xFFB41522),
        highlight = AkraColors.Amber,
    ),
    GarageTheme(
        id = "bmw-m",
        name = "BMW M",
        subtitle = "Black base with blue, violet, and red motorsport stripes.",
        base = Color(0xFF07090D),
        surface = Color(0xFF121721),
        accent = Color(0xFF2D9CDB),
        secondaryAccent = Color(0xFF7B3FF2),
        highlight = Color(0xFFE21B2D),
    ),
    GarageTheme(
        id = "mercedes-amg",
        name = "Mercedes-AMG",
        subtitle = "Obsidian cockpit with silver edgework and green performance spark.",
        base = Color(0xFF070807),
        surface = Color(0xFF151716),
        accent = Color(0xFFD7DCE2),
        secondaryAccent = Color(0xFF00A859),
        highlight = AkraColors.Amber,
    ),
    GarageTheme(
        id = "porsche",
        name = "Porsche",
        subtitle = "Deep black, guards red, warm ivory instrument highlights.",
        base = Color(0xFF090909),
        surface = Color(0xFF151311),
        accent = Color(0xFFEACD8A),
        secondaryAccent = Color(0xFFD5001C),
        highlight = AkraColors.Amber,
    ),
    GarageTheme(
        id = "volkswagen-r",
        name = "Volkswagen R",
        subtitle = "Dark cabin with electric blue performance accent.",
        base = Color(0xFF070A10),
        surface = Color(0xFF101826),
        accent = Color(0xFF4EA3FF),
        secondaryAccent = Color(0xFF95B8FF),
        highlight = AkraColors.Pearl,
    ),
    GarageTheme(
        id = "lamborghini",
        name = "Lamborghini",
        subtitle = "Stealth black with sharp green and amber supercar contrast.",
        base = Color(0xFF060806),
        surface = Color(0xFF111611),
        accent = Color(0xFFB4FF00),
        secondaryAccent = Color(0xFFFFD54A),
        highlight = AkraColors.Pearl,
    ),
)
